<MyLayout>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        #padding: 15
        #spacing: 20 #spacing between widgets
        FloatLayout:
            canvas.before:
                Color:
                    rgba: 1, 0, 0, 1  # Color de la línea (en este caso rojo)
                Line:
                    rectangle: self.x, self.y, self.width, self.height
                    width: 7  # Ancho de la línea

            canvas.after:
                Color:
                    rgba: 0, 1, 0, 1  # Color de la línea (en este caso verde)
                Line:
                    points:10,30,90,90,90,50,30,10
                
            Image:
                source: 'Ciclo_rakine_1.png'
                allow_stretch: True
                keep_ratio: True
                size_hint: None, None  # Establece el tamaño de la imagen a su tamaño original
                size: self.texture_size  # Establece el tamaño a las dimensiones reales de la imagen
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}  # Posiciona la imagen en el centro del FloatLayout
            #lines Test
            