<Button>
    font_size: 50
    size_hint: 0.2, 0.2
<MyLayout>
    #Grid general de toda la pantalla 
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        padding: 15
        spacing: 20 #spacing between widgets
        #GRid general de tres Columnas
        GridLayout:
            cols: 3
            spacing: 20
            #Columna 1 - Datos de Entrada 
            #Primera Columna donde estaran los datos de entrada
            GridLayout:
                cols:2
                size_hint: (.25, 1)
                padding: 15
                spacing: 20 #spacing between widgets
                Label:
                    text:'Presión a la salida del condensador en Pa'
                    color:(0,0,0,1)
                    font_size: 20
                TextInput:
                    id: p1
                    multiline: False
                    font_size: 20
                    input_filter: 'float'
                    on_text_validate: root.calcular()
                Label:
                    text:'Calidad salida del condensador'
                    color:(0,0,0,1)
                    font_size: 20
                TextInput:
                    id: x1
                    multiline: False
                    font_size: 20
                    input_filter: 'float'
                    on_text_validate: root.calcular()
                Label:
                    text:'Presión a la salida de la segunda bomba en Pa'
                    color:(0,0,0,1)
                    font_size: 20
                TextInput:
                    id: p2
                    multiline: False
                    font_size: 20
                    input_filter: 'float'
                    on_text_validate: root.calcular()
                Label:
                    text:'Presión a la salida del calentador de agua de alimentación baja en Pa'
                    color:(0,0,0,1)
                    font_size: 20
                TextInput:
                    id: p3
                    multiline: False
                    font_size: 20
                    input_filter: 'float'
                    on_text_validate: root.calcular()
                Label:
                    text:'Condensación completa en el calentador cerrado de agua de alimentación'
                    color:(0,0,0,1)
                    font_size: 20
                TextInput:
                    id: x3
                    multiline: False
                    font_size: 20
                    input_filter: 'float'
                    on_text_validate: root.calcular()
                Label:
                    text:'Temperatura en la salida de la caldera/entrada de la turbina en °C'
                    color:(0,0,0,1)
                    font_size: 20
                TextInput:
                    id: T6
                    multiline: False
                    font_size: 20
                    input_filter: 'float'
                    on_text_validate: root.calcular()
                Label:
                    text:'Flujo masico en kg/s'
                    color:(0,0,0,1)
                    font_size: 20
                TextInput:
                    id: mp
                    multiline: False
                    font_size: 20
                    input_filter: 'float'
                    on_text_validate: root.calcular()
                Label:
                    text:'Eficiencia para las bombas'
                    color:(0,0,0,1)
                    font_size: 20
                TextInput:
                    id: nb
                    multiline: False
                    font_size: 20
                    input_filter: 'float'
                    on_text_validate: root.calcular()
                Label:
                    text:'Eficiencia de la turbina'
                    color:(0,0,0,1)
                    font_size: 20
                TextInput:
                    id: nt
                    multiline: False
                    font_size: 20
                    input_filter: 'float'
                    on_text_validate: root.calcular()

            #Columna 2 - Titulo del Programa y el Dibujo del Ciclo
            GridLayout:
                cols: 1
                spacing: 20
                size_hint: (.5, 1)
                padding: 15
                spacing: 20 
                #Fila 1
                GridLayout:
                    cols: 1
                    spacing: 20
                    #Boton +
                    Button:
                        text: '+'
                    #Boton -
                    Button:
                        text: '-'
                    #Boton *
                    Button:
                        text: '*'
                #Fila 2
                GridLayout:
                    cols: 1
                    spacing: 20
                    #Boton /
                    Button:
                        text: '/'
                    #Boton (
                    Button:
                        text: '('
                    #Boton )
                    Button:
                        text: ')'
                #Fila 3
                GridLayout:
                    cols: 1
                    spacing: 20
                    #Boton sin
                    Button:
                        text: 'sin'
                    #Boton cos
                    Button:
                        text: 'cos'
                    #Boton tan
                    Button:
                        text: 'tan'
                #Fila 4
                GridLayout:
                    cols: 1
                    spacing: 20
                    #Boton log
                    Button:
                        text: 'log'
                    #Boton ln
                    Button:
                        text: 'ln'
                    #Boton ^
                    Button:
                        text: '^'
            #Columna 3 - Resultados y grafico de Porcentaje 
            GridLayout:
                cols: 1
                spacing: 20
                size_hint: (.25, 1)
                padding: 15
                #Fila 1
                GridLayout:
                    cols: 1
                    spacing: 20
                    #Boton C
                    Button:
                        text: 'C'
                    #Boton CE
                    Button:
                        text: 'CE'
                    #Boton DEL
                    Button:
                        text: 'DEL'
                #Fila 2
                GridLayout:
                    cols: 1
                    spacing: 20
                    #Boton x!
                    Button:
                        text: 'x!'
                    #Boton x^2
                    Button:
                        text: 'x^2'
                    #Boton x^3
                    Button:
                        text: 'x^3'
                #Fila 3
                GridLayout:
                    cols: 1
                    spacing: 20
                    #Boton x^y
                    Button:
                        text: 'x^y'
                    #Boton 10^x
                    Button:
                        text: '10^x'
                    #Boton 2^x
                    Button:
                        text: '2^x'
                #Fila 4
                GridLayout:
                    cols: 1
                    spacing: 20
                    #Boton sqrt
                    Button:
                        text: 'sqrt'
                    #Boton cbrt
                    Button:
                        text: 'cbrt'
                    #Boton pi
                    Button:
                        text: 'pi'