<MyLayout>:
    canvas.before:
        Color:
            rgba: 1, 0, 0, 1  # Color rojo para la línea (RGBA)
        #Line base
        Line:
            points: [100, 100, root.length + 100, 100]  # Uso de la propiedad length
            width: 4  # Ancho de la línea
        #Linea top
        Line:
            points: [800, 800, 800 + 100, 900]  # Uso de la propiedad length
            width: 4  # Ancho de la línea
        #Linea left
        Line:
            points: [100, 100, 100, 100 + 100]  # Uso de la propiedad length
            width: 4  # Ancho de la línea
